In [1]:
import cv2
import numpy as np
import kociemba
import matplotlib.pyplot as plt

In [2]:
# global variables
x1, x2 = 325, 955
y1, y2 = 45, 675
cell_size = 210
cx = 640
cy = 360

In [2]:
def get_cell_centers():
    cell_centers=[]

    cell_centers.append((cx - cell_size, cy - cell_size)) #top left
    cell_centers.append((cx, cy - cell_size)) #top center
    cell_centers.append((cx + cell_size, cy - cell_size)) #top right
    cell_centers.append((cx - cell_size, cy)) #left middle
    cell_centers.append((cx, cy)) #center
    cell_centers.append((cx + cell_size, cy)) #right middle
    cell_centers.append((cx - cell_size, cy + cell_size)) #bottom left
    cell_centers.append((cx, cy + cell_size)) #bottomn center
    cell_centers.append((cx + cell_size, cy + cell_size)) #bottom right

    return cell_centers

In [7]:
def draw_template(frame):
    color=(0,0,255)
    thickness = 5
    color_blue = (255,0,0)

    cv2.line(frame, (x1,y1), (x2,y1), color, thickness) #top
    cv2.line(frame, (x1,y1), (x1,y2), color, thickness) #left
    cv2.line(frame, (x1,y2), (x2,y2), color, thickness) #bottom
    cv2.line(frame, (x2,y1), (x2,y2), color, thickness) #right

    cv2.line(frame, (x1, y1+cell_size), (x2, y1+cell_size), color, thickness) #horizontal 1
    cv2.line(frame, (x1, y1+(cell_size*2)), (x2, y1+(cell_size*2)), color, thickness) #horizontal 2
    cv2.line(frame, (x1+cell_size, y1), (x1+cell_size, y2), color, thickness) #vertical 1
    cv2.line(frame, (x1+(cell_size*2), y1), (x1+(cell_size*2), y2), color, thickness) #vertical 2

    height, width, _ = frame.shape
    cx = width // 2
    cy = height // 2

    # cv2.circle(image, center_coordinates, radius, color, thickness)
    cv2.circle(frame, (cx, cy), 10, color_blue, thickness)
    cv2.circle(frame, (cx + cell_size, cy), 10, color_blue, thickness)
    cv2.circle(frame, (cx - cell_size, cy), 10, color_blue, thickness)
    cv2.circle(frame, (cx, cy + cell_size), 10, color_blue, thickness)
    cv2.circle(frame, (cx + cell_size, cy + cell_size), 10, color_blue, thickness)
    cv2.circle(frame, (cx - cell_size, cy + cell_size), 10, color_blue, thickness)
    cv2.circle(frame, (cx, cy - cell_size), 10, color_blue, thickness)
    cv2.circle(frame, (cx + cell_size, cy - cell_size), 10, color_blue, thickness)
    cv2.circle(frame, (cx - cell_size, cy - cell_size), 10, color_blue, thickness)


  
    plt.imshow(frame)
    plt.show()
    

new code

In [2]:
import cv2
import numpy as np
import kociemba
import matplotlib.pyplot as plt

In [3]:
def get_cell_centers():
    cell_centers=[]

    cell_centers.append((cx - cell_size, cy - cell_size)) #top left
    cell_centers.append((cx, cy - cell_size)) #top center
    cell_centers.append((cx + cell_size, cy - cell_size)) #top right
    cell_centers.append((cx - cell_size, cy)) #left middle
    cell_centers.append((cx, cy)) #center
    cell_centers.append((cx + cell_size, cy)) #right middle
    cell_centers.append((cx - cell_size, cy + cell_size)) #bottom left
    cell_centers.append((cx, cy + cell_size)) #bottomn center
    cell_centers.append((cx + cell_size, cy + cell_size)) #bottom right

    return cell_centers

In [4]:
#changing thE TEMPLATE
x1, x2 = 425, 900
y1, y2 = 150, 600
cell_size = 158
cx = 662
cy = 382

def draw_template(frame):
    thickness = 5
    color = (0,255,0)

    # cv2.circle(image, center_coordinates, radius, color, thickness)
    #top row
    cv2.circle(frame, (cx - cell_size - 30, cy - cell_size - 30), 10, color, thickness)
    cv2.circle(frame, (cx, cy - cell_size - 30), 10, color, thickness)
    cv2.circle(frame, (cx + cell_size + 30, cy - cell_size - 30), 10, color, thickness)

    #middle row
    cv2.circle(frame, (cx - cell_size - 30, cy), 10, color, thickness)
    cv2.circle(frame, (cx, cy), 10, color, thickness)
    cv2.circle(frame, (cx + cell_size + 30, cy), 10, color, thickness)

    #bottom row
    cv2.circle(frame, (cx - cell_size - 30, cy + cell_size + 30), 10, color, thickness)
    cv2.circle(frame, (cx, cy + cell_size + 30), 10, color, thickness)
    cv2.circle(frame, (cx + cell_size + 30, cy + cell_size + 30), 10, color, thickness)


  
    # plt.imshow(frame)
    # plt.show()
    

In [5]:
draw_template(cv2.imread("img/face_1.png"))

In [6]:
def start_video():
    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

    face_count  = 0

    while True:
        _, frame = cap.read()
        hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        cell_centers = get_cell_centers()

        draw_template(frame)
        
        cv2.imshow('frame', frame)

        #take ss
        key = cv2.waitKey(1)
        if key == ord('s'):
            img_name = "img/face_" + str(face_count + 1) + ".png"
            cv2.imwrite(img_name, frame)
            print("saving file", img_name)

            face_count += 1

        if face_count == 6:
            print("got all sides")
            break

        #quit out
        key = cv2.waitKey(1) 
        if key == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

    return cell_centers

In [7]:

start_video()

saving file img/face_1.png
saving file img/face_2.png
saving file img/face_3.png
saving file img/face_4.png
saving file img/face_5.png
saving file img/face_6.png
got all sides


[(504, 224),
 (662, 224),
 (820, 224),
 (504, 382),
 (662, 382),
 (820, 382),
 (504, 540),
 (662, 540),
 (820, 540)]

: 

In [39]:
def get_color(hsv):
    hue = hsv[0]
    saturation = hsv[1]
    value = hsv[2]

    color = None
    if hue < 5:
        color = "R"
    elif hue < 22:
        color = "O"
    elif hue < 33:
        color = "Y"
    elif hue < 90:
        color = "G"
    elif hue < 131:
        color = "B"
    elif hue < 180:
        color = "R"
    else:
        color = "W"

    if saturation < 65:
        color = "W"

    return color

In [40]:
def color_detect(frame, cell_centers):
    cell_colors = []
    hue_values = []
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    c00 = hsv_frame[ cell_centers[0][1], cell_centers[0][0]]
    color00 = get_color(c00)

    c01 = hsv_frame[ cell_centers[1][1], cell_centers[1][0]]
    color01 = get_color(c01)

    c02 = hsv_frame[ cell_centers[2][1], cell_centers[2][0]]
    color02 = get_color(c02)

    c10 = hsv_frame[ cell_centers[3][1], cell_centers[3][0]]
    color10 = get_color(c10)

    c11 = hsv_frame[ cell_centers[4][1], cell_centers[4][0]]
    color11 = get_color(c11)

    c12 = hsv_frame[cell_centers[5][1], cell_centers[5][0]]
    color12 = get_color(c12)

    c20 = hsv_frame[ cell_centers[6][1], cell_centers[6][0]]
    color20 = get_color(c20)

    c21 = hsv_frame[ cell_centers[7][1], cell_centers[7][0]]
    color21 = get_color(c21)

    c22 = hsv_frame[ cell_centers[8][1], cell_centers[8][0]]
    color22 = get_color(c22)

    cell_colors.append(color00)
    cell_colors.append(color01)
    cell_colors.append(color02)
    cell_colors.append(color10)
    cell_colors.append(color11)
    cell_colors.append(color12)
    cell_colors.append(color20)
    cell_colors.append(color21)
    cell_colors.append(color22)

    hue_values.append(c00)
    hue_values.append(c01)
    hue_values.append(c02)
    hue_values.append(c10)
    hue_values.append(c11)
    hue_values.append(c12)
    hue_values.append(c20)
    hue_values.append(c21)
    hue_values.append(c22)

    return cell_colors, hue_values

In [41]:
cell_centers = get_cell_centers()

f1, h1 = color_detect(cv2.imread('img/face_1.png'), cell_centers)
f2, h2 = color_detect(cv2.imread('img/face_2.png'), cell_centers)
f3, h3 = color_detect(cv2.imread('img/face_3.png'), cell_centers)
f4, h4 = color_detect(cv2.imread('img/face_4.png'), cell_centers)
f5, h5 = color_detect(cv2.imread('img/face_5.png'), cell_centers)
f6, h6 = color_detect(cv2.imread('img/face_6.png'), cell_centers)

f1[4] = 'W'

In [42]:
f1

['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']

In [43]:
#prints out flattened out version of cube
def chunk_face(f):
    return [f[x:x+3] for x in range(0, len(f), 3)]

def net_cube(f1, f2, f3, f4, f5, f6):
    top = chunk_face(f1)
    print(" "*7, "- "*5)
    print(" "*7, "|", top[0][0], top[0][1], top[0][2], "|")
    print(" "*7, "|", top[1][0], top[1][1], top[1][2], "|")
    print(" "*7, "|", top[2][0], top[2][1], top[2][2], "|")
    print(" "*7, "- "*5)

    left = chunk_face(f5)
    front = chunk_face(f3)
    right = chunk_face(f2)
    back = chunk_face(f6)
    print("- "*17)
    print("|", left[0][0], left[0][1], left[0][2], "|", front[0][0], front[0][1], front[0][2], "|", right[0][0], right[0][1], right[0][2], "|", back[0][0], back[0][1], back[0][2], "|")
    print("|", left[1][0], left[1][1], left[1][2], "|", front[1][0], front[1][1], front[1][2], "|", right[1][0], right[1][1], right[1][2], "|", back[1][0], back[1][1], back[1][2], "|")
    print("|",left[2][0], left[2][1], left[2][2], "|", front[2][0], front[2][1], front[2][2], "|", right[2][0], right[2][1], right[2][2], "|", back[2][0], back[2][1], back[2][2], "|")
    print("- "*17)

    down = chunk_face(f4)
    print(" "*7, "- "*5)
    print(" "*7, "|", down[0][0], down[0][1], down[0][2], "|")
    print(" "*7, "|", down[1][0], down[1][1], down[1][2], "|")
    print(" "*7, "|", down[2][0], down[2][1], down[2][2], "|")
    print(" "*7, "- "*5)




net_cube(f1, f2, f3, f4, f5, f6)

        - - - - - 
        | W W W |
        | W W W |
        | W W W |
        - - - - - 
- - - - - - - - - - - - - - - - - 
| O O O | G G G | R R R | B B B |
| O O O | G G G | R R R | B B B |
| O O O | G G G | R R R | B B B |
- - - - - - - - - - - - - - - - - 
        - - - - - 
        | Y Y Y |
        | Y Y Y |
        | Y Y Y |
        - - - - - 


In [44]:
f1

['W', 'W', 'W', 'W', 'W', 'W', 'W', 'W', 'W']

In [45]:
h1

[array([117,  44, 255], dtype=uint8),
 array([116,  48, 255], dtype=uint8),
 array([117,  53, 249], dtype=uint8),
 array([114,  47, 255], dtype=uint8),
 array([111, 255, 141], dtype=uint8),
 array([117,  61, 252], dtype=uint8),
 array([115,  49, 255], dtype=uint8),
 array([116,  56, 255], dtype=uint8),
 array([116,  61, 243], dtype=uint8)]

: 

In [32]:
f1 = ['R','W','W','R','W','W','B','B','B']
f2 = ['R','G','G','R','R','Y','R','R','Y']
f3 = ['W','W','W','W','G','G','W','G','G']
f4 = ['G','Y','Y','G','Y','Y','G','O','O']
f5 = ['B','B','O','O','O','O','O','O','O']
f6 = ['R','R','Y','B','B','Y','B','B','Y']

net_cube(f1, f2, f3, f4, f5, f6)

kociemba_input = ''
kociemba_input += list_to_string(f1)
kociemba_input += list_to_string(f2)
kociemba_input += list_to_string(f3)
kociemba_input += list_to_string(f4)
kociemba_input += list_to_string(f5)
kociemba_input += list_to_string(f6)

rubiks_face = translate_string(kociemba_input)
kociemba.solve(rubiks_face)

        - - - - - 
        | R W W |
        | R W W |
        | B B B |
        - - - - - 
- - - - - - - - - - - - - - - - - 
| B B O | W W W | R G G | R R Y |
| O O O | W G G | R R Y | B B Y |
| O O O | W G G | R R Y | B B Y |
- - - - - - - - - - - - - - - - - 
        - - - - - 
        | G Y Y |
        | G Y Y |
        | G O O |
        - - - - - 
original string:  RWWRWWBBBRGGRRYRRYWWWWGGWGGGYYGYYGOOBBOOOOOOORRYBBYBBY
kociemba.solve('RUURUUBBBRFFRRDRRDUUUUFFUFFFDDFDDFLLBBLLLLLLLRRDBBDBBD')


"U L' B'"

In [31]:
def list_to_string(l):
    return ''.join(i for i in l)

def validate_string(str):
	if len(str) != 54:
		print("string isn't long enough")
		return False

	if str.count('U') != 9:
		print("not enough U's")
		return False

	if str.count('R') != 9:
		print("not enough R's")
		return False

	if str.count('F') != 9:
		print("not enough F's")
		return False

	if str.count('D') != 9:
		print("not enough D's")
		return False

	if str.count('L') != 9:
		print("not enough L's")
		return False

	if str.count('B') != 9:
		print("not enough B's")
		return False

	return True



def translate_string(rubiks_str):
# def translate_string():
	mydict = {  ord("W"):ord("U"), 
	   			ord("Y"):ord("D"),
				ord("R"):ord("R"),
				ord("O"):ord("L"), 
				ord("G"):ord("F"), 
				ord("B"):ord("B") }

	print("original string: ", rubiks_str)

	input_string = rubiks_str.translate(mydict)

	if not validate_string(input_string):
		print("not valid string")
		exit(1)

	print("kociemba.solve('"+ input_string + "')")

	return input_string

# rubiks_face = translate_string()
# kociemba.solve(rubiks_face)



In [24]:
kociemba_input = ''
kociemba_input += list_to_string(f1)
kociemba_input += list_to_string(f2)
kociemba_input += list_to_string(f3)
kociemba_input += list_to_string(f4)
kociemba_input += list_to_string(f5)
kociemba_input += list_to_string(f6)

In [25]:
rubiks_face = translate_string(kociemba_input)
kociemba.solve(rubiks_face)

original string:  WBGWWRRORGBWOROORYYYWGGWOWYBGGGYYBROBBGYORRYWOORGBBBWY
kociemba.solve('UBFUURRLRFBULRLLRDDDUFFULUDBFFFDDBRLBBFDLRRDULLRFBBBUD')


"U R' B' U2 L B D2 R2 B R' B D L2 F2 R2 D2 B2 U R2 D F2"

: 

In [41]:
rubiks_face = translate_string('YOWGWGYWYGYORRRYYBBGRWGBGOBWGRWYOBBWOROROOOBRGBGYBWRYW')
kociemba.solve(rubiks_face)

original string:  YOWGWGYWYGYORRRYYBBGRWGBGOBWGRWYOBBWOROROOOBRGBGYBWRYW
kociemba.solve('DLUFUFDUDFDLRRRDDBBFRUFBFLBUFRUDLBBULRLRLLLBRFBFDBURDU')


"D' R' F' L' D2 L' F2 B' L B2 U2 R2 F2 L2 D2 L2 F2"

In [7]:
rubiks_face = translate_string('WWWWWWWWWRRRRRRRRRGGGGGGGGGYYYYYYYYYOOOOOOOOOBBBBBBBBB')
kociemba.solve(rubiks_face)

original string:  WWWWWWWWWRRRRRRRRRGGGGGGGGGYYYYYYYYYOOOOOOOOOBBBBBBBBB
kociemba.solve('UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB')


"R L U2 R L' B2 U2 R2 F2 L2 D2 L2 F2"

In [ ]:
horizonal faces: 
L F R B

vertical faces:
U D

x R, y W, z G,

turn R/right, you can get to F U D 
turn W/top, you can get to L F R B

In [24]:
'''
    moves to make:
    - face rotations:
        90,
        180 aka 90x2
        -90
    - cube movements:
        +v, -v
        +h, -h
'''

#permutations
orientation_translate = {
        'UD' : "vv",
        'DU' : "VV",
        'UL' : "vh",
        'LU' : "VH",
        "UR" : "vH",
        'RU' : "Vh",
        "UF" : "v",
        "FU" : "V",
        "UB" : "vv",
        "BU" : "VV",
        "DL" : "Vh",
        "LD" : "vH",
        "DR" : "VH",
        "RD" : "vh",
        "DF" : "VV",
        "FD" : "vv",
        "DB" : "Vhh",
        "BD" : "vHH",
        "LR" : "HH",
        "RL" : "hh",
        "LF" : "HVV",
        "FL" : "hvv",
        "LB" : "Hv",
        "BL" : "hV",
        "RF" : "h",
        "FR" : "H",
        "RB" : "H",
        "BR" : "h",
        "FB" : "HH",
        "BF" : "hh"
}

In [25]:
a = "R L U2 R L' B2 U2 R2 F2 L2 D2 L2 F2"
moves = list(a.split(' '))

In [26]:
moves

['R', 'L', 'U2', 'R', "L'", 'B2', 'U2', 'R2', 'F2', 'L2', 'D2', 'L2', 'F2']

In [27]:
orientation = 'F'

for m in moves:
    new_orientation = orientation + m
    print(new_orientation)
    print("translation:", new_orientation.translate(orientation_translate))

    orientation = m

FR
translation: FR
RL
translation: RL
LU2
translation: LU2
U2R
translation: U2R
RL'
translation: RL'
L'B2
translation: L'B2
B2U2
translation: B2U2
U2R2
translation: U2R2
R2F2
translation: R2F2
F2L2
translation: F2L2
L2D2
translation: L2D2
D2L2
translation: D2L2
L2F2
translation: L2F2


In [28]:
"FR".translate(orientation_translate)

'FR'

In [46]:
orientation = ['U','F','R'] #W, G, R

orient_translate = {

}
    
def update_orientation(type, face):
    global orientation

    if type == "top":
        print("\tpick up block from top side and turn face 180")
        if orientation[1] == 'F':
            orientation = [orientation[0],'B','L'] #W, B, O
        elif orientation[1] == 'B':
            orientation = ['U','F','R'] #W, G, R
        print(f"\tmove {face}")

    elif type == "right":
        print("\tpick up block from right side and turn 180")
        if orientation[0] == 'U':
            orientation = ['F','D',orientation[2]] #G, Y, R
        elif orientation[1] == 'Y':
            orientation = ['U','F',orientation[2]] #G, Y, R
        print(f"\tmove {face}")


for m in new_moves:
    print(f"for move {m}:")
    if m in orientation:
        print(f"turn {m} face")

    else:
        if m in ['F', 'U', 'D']:
            print("turn by right face")
            update_orientation("right", m)
        elif m in ['L', 'R', 'B']:
            print("turn by top face")
            update_orientation("top", m)

    print(orientation, "\n")

for move R:
turn R face
['U', 'F', 'R'] 

for move L:
turn by top face
	pick up block from top side and turn face 180
	move L
['U', 'B', 'L'] 

for move U:
turn U face
['U', 'B', 'L'] 

for move R:
turn by top face
	pick up block from top side and turn face 180
	move R
['U', 'F', 'R'] 

for move L:
turn by top face
	pick up block from top side and turn face 180
	move L
['U', 'B', 'L'] 

for move B:
turn B face
['U', 'B', 'L'] 

for move U:
turn U face
['U', 'B', 'L'] 

for move R:
turn by top face
	pick up block from top side and turn face 180
	move R
['U', 'F', 'R'] 

for move F:
turn F face
['U', 'F', 'R'] 

for move L:
turn by top face
	pick up block from top side and turn face 180
	move L
['U', 'B', 'L'] 

for move D:
turn by right face
	pick up block from right side and turn 180
	move D
['F', 'D', 'L'] 

for move L:
turn L face
['F', 'D', 'L'] 

for move F:
turn F face
['F', 'D', 'L'] 



In [34]:
new_moves=[]
for m in moves:
    new_moves.append(m[0])

new_moves

['R', 'L', 'U', 'R', 'L', 'B', 'U', 'R', 'F', 'L', 'D', 'L', 'F']

In [43]:
moves

['R', 'L', 'U2', 'R', "L'", 'B2', 'U2', 'R2', 'F2', 'L2', 'D2', 'L2', 'F2']